// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LongArithmetic.BddTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Multiplication algorithm selection under load")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("bdd")]
    [global::NUnit.Framework.CategoryAttribute("multiplication")]
    [global::NUnit.Framework.CategoryAttribute("load")]
    public partial class MultiplicationAlgorithmSelectionUnderLoadFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "bdd",
                "multiplication",
                "load"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Multiplication algorithm selection under load", "  As a performance engineer\n  I want to compare classic and Karatsuba multiplicat" +
                "ion on representative datasets\n  So that I can choose a reliable strategy for he" +
                "avy long arithmetic calculations", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "MultiplicationPerformance.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("the multiplication algorithms \"classic\" and \"karatsuba\" are available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MultiplicationPerformance.feature.ndjson", 8);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Baseline comparison matches the current unit-test oracle")]
        public async global::System.Threading.Tasks.Task BaselineComparisonMatchesTheCurrentUnit_TestOracle()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Baseline comparison matches the current unit-test oracle", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Both multiplication algorithms must always return the same product", null, tagsOfRule);
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
      await testRunner.GivenAsync("the operands are \"9999999999999999999999999999999999999999\" and \"8888888888888888" +
                        "888888888888888888888888\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
      await testRunner.WhenAsync("I multiply the numbers using \"classic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
      await testRunner.AndAsync("I multiply the numbers using \"karatsuba\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
      await testRunner.ThenAsync("the algorithm results should match", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
      await testRunner.AndAsync("the multiplication result should satisfy the unit-test comparison oracle", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Benchmark both multiplication algorithms on representative datasets")]
        [global::NUnit.Framework.TestCaseAttribute("dense", "40", "1000", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("dense", "120", "3000", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("sparse", "40", "1000", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("sparse", "120", "3000", "4", null)]
        public async global::System.Threading.Tasks.Task BenchmarkBothMultiplicationAlgorithmsOnRepresentativeDatasets(string profile, string digits, string maxMilliseconds, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("profile", profile);
            argumentsOfScenario.Add("digits", digits);
            argumentsOfScenario.Add("maxMilliseconds", maxMilliseconds);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Benchmark both multiplication algorithms on representative datasets", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Preliminary load experiments should cover different data profiles and sizes", null, tagsOfRule);
#line 19
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
      await testRunner.GivenAsync(string.Format("multiplication inputs generated for \"{0}\" data with {1} digits per operand", profile, digits), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
      await testRunner.WhenAsync("I benchmark multiplication algorithm \"classic\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
      await testRunner.AndAsync("I benchmark multiplication algorithm \"karatsuba\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
      await testRunner.ThenAsync("the algorithm results should match", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
      await testRunner.AndAsync("the timings should be collected for all benchmarked algorithms", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
      await testRunner.ButAsync(string.Format("each benchmark should finish within {0} milliseconds", maxMilliseconds), ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
#line 26
      await testRunner.AndAsync(string.Format("the benchmark profile should be recorded as \"{0}\" with size {1}", profile, digits), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preliminary experiment identifies the largest safe candidate size")]
        public async global::System.Threading.Tasks.Task PreliminaryExperimentIdentifiesTheLargestSafeCandidateSize()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preliminary experiment identifies the largest safe candidate size", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Preliminary load experiments should cover different data profiles and sizes", null, tagsOfRule);
#line 35
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Digits"});
                table1.AddRow(new string[] {
                            "40"});
                table1.AddRow(new string[] {
                            "120"});
                table1.AddRow(new string[] {
                            "240"});
#line 36
      await testRunner.GivenAsync("the candidate multiplication sizes are", ((string)(null)), table1, "Given ");
#line hidden
#line 41
      await testRunner.WhenAsync("I run the preliminary multiplication experiment for \"dense\" data", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
      await testRunner.ThenAsync("a maximal safe multiplication size should be selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
      await testRunner.AndAsync("the selected size should be at least 40 digits", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
      await testRunner.ButAsync("the full experiment should finish within 30000 milliseconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
